// <auto-generated />
namespace CapstoneRemastered.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedvehicleKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedvehicleKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201606081729495_Added vehicle Keys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
